v0.3.0

diff --git a/git/ess/part-10 b/git/ess/part-10
--- a/git/ess/part-10
+++ b/git/ess/part-10
@@ -6,37 +6,37 @@ verbosity=$2
 out="/var/fenrir/out"
 err="/var/fenrir/err"
 
-log info "$verbosity" "P10: Validating commits tree.."
+fenrir-log info "$verbosity" "P10: Validating commits tree.."
 
-if ! change-branch "$repo" "$verbosity" "16"; then
-    log err "$verbosity" "P10: Terminating.."
+if ! fenrir-change-branch "$repo" "$verbosity" "16"; then
+    fenrir-log err "$verbosity" "P10: Terminating.."
     exit 1
 fi
 
 log info "$verbosity" "P10: Validating file mode.."
 
-if [ "$(file-type win.sh)" != '100755' ]; then
-    log err "$verbosity" "P10: Invalid file mode"
+if [ "$(fenrir-file-type win.sh)" != '100755' ]; then
+    fenrir-log err "$verbosity" "P10: Invalid file mode"
     exit 1
 fi
 
-log info "$verbosity" "P10: Executing script.."
+fenrir-log info "$verbosity" "P10: Executing script.."
 
 if ! ./win.sh > "$out" 2> "$err"; then
-    log err "$verbosity"  "Failed"
-    log warn "$verbosity" "<stdout>" "$(cat "$out")"
-    log err "$verbosity"  "<stderr>" "$(cat "$err")"
+    fenrir-log err "$verbosity"  "Failed"
+    fenrir-log warn "$verbosity" "<stdout>" "$(cat "$out")"
+    fenrir-log err "$verbosity"  "<stderr>" "$(cat "$err")"
     exit 1
 fi
 
 if [ "$(cat "$out")" != "HI" ] &&
    [ -n "$(cat "$err")" ]; then
-    log err "$verbosity"  "Something went wrong:"
-    log warn "$verbosity" "<stdout>" "$(cat "$out")"
-    log err "$verbosity"  "<stderr>" "$(cat "$err")"
+    fenrir-log err "$verbosity"  "Something went wrong:"
+    fenrir-log warn "$verbosity" "<stdout>" "$(cat "$out")"
+    fenrir-log err "$verbosity"  "<stderr>" "$(cat "$err")"
     exit 1
 fi
 
-add-points "$points"
+fenrir-add-points "$points"
 
-log succ "$verbosity" "P10: PASSED"
+fenrir-log succ "$verbosity" "P10: PASSED"
diff --git a/git/ess/part-11 b/git/ess/part-11
--- a/git/ess/part-11
+++ b/git/ess/part-11
@@ -6,125 +6,125 @@ verbosity=$2
 out="/var/fenrir/out"
 err="/var/fenrir/err"
 
-log info "$verbosity" "P11: Validating commits tree.."
+fenrir-log info "$verbosity" "P11: Validating commits tree.."
 
-if ! change-branch "$repo" "$verbosity" "17"; then
-    log err "$verbosity" "P11: Terminating.."
+if ! fenrir-change-branch "$repo" "$verbosity" "17"; then
+    fenrir-log err "$verbosity" "P11: Terminating.."
     exit 1
 fi
 
-log info "$verbosity" "P11: Searching script.."
+fenrir-log info "$verbosity" "P11: Searching script.."
 
 if ! [ -x "install" ]; then
-    log err "$verbosity" "P11: 'install' was not found"
+    fenrir-log err "$verbosity" "P11: 'install' was not found"
     exit 1
 fi
 
-log succ "$verbosity" "P11: 'install' was found"
+fenrir-log succ "$verbosity" "P11: 'install' was found"
 
-log info "$verbosity" "P11: Installing hooks.."
+fenrir-log info "$verbosity" "P11: Installing hooks.."
 
 if ! ./install > "$out" 2> "$err"; then
-    log err "$verbosity"  "Failed"
-    log warn "$verbosity" "<stdout>" "$(cat "$out")"
-    log err "$verbosity"  "<stderr>" "$(cat "$err")"
+    fenrir-log err "$verbosity"  "Failed"
+    fenrir-log warn "$verbosity" "<stdout>" "$(cat "$out")"
+    fenrir-log err "$verbosity"  "<stderr>" "$(cat "$err")"
     exit 1
 fi
 
-log succ "$verbosity" "P11: Installed"
+fenrir-log succ "$verbosity" "P11: Installed"
 
-log info "$verbosity" "P11: Creating file 'file'.."
+fenrir-log info "$verbosity" "P11: Creating file 'file'.."
 touch file
 
-log info "$verbosity" "P11: Running 'git add file'.."
+fenrir-log info "$verbosity" "P11: Running 'git add file'.."
 git add file
 
-log info "$verbosity" "P11: Running 'git commit -m \"BAD MESSAGE\"'.."
+fenrir-log info "$verbosity" "P11: Running 'git commit -m \"BAD MESSAGE\"'.."
 if git commit -m "BAD MESSAGE" > "$out" 2> "$err"; then
-    log err "$verbosity" "File has been commited!"
-    log warn "$verbosity" "<stdout>" "$(cat "$out")"
-    log err "$verbosity"  "<stderr>" "$(cat "$err")"
+    fenrir-log err "$verbosity" "File has been commited!"
+    fenrir-log warn "$verbosity" "<stdout>" "$(cat "$out")"
+    fenrir-log err "$verbosity"  "<stderr>" "$(cat "$err")"
     exit 1
 fi
-log succ "$verbosity" "P11: Hook works correct"
+fenrir-log succ "$verbosity" "P11: Hook works correct"
 
-log info "$verbosity" "P11: Running 'git commit -m \"[FIX] BAD\"'.."
+fenrir-log info "$verbosity" "P11: Running 'git commit -m \"[FIX] BAD\"'.."
 if git commit -m "[FIX] BAD" > "$out" 2> "$err"; then
-    log err "$verbosity" "File has been commited!"
-    log warn "$verbosity" "<stdout>" "$(cat "$out")"
-    log err "$verbosity"  "<stderr>" "$(cat "$err")"
+    fenrir-log err "$verbosity" "File has been commited!"
+    fenrir-log warn "$verbosity" "<stdout>" "$(cat "$out")"
+    fenrir-log err "$verbosity"  "<stderr>" "$(cat "$err")"
     exit 1
 fi
-log succ "$verbosity" "P11: Hook works correct"
+fenrir-log succ "$verbosity" "P11: Hook works correct"
 
-log info "$verbosity" "P11: Running 'git commit -m \"[ АDD ] Tricky\"'.."
+fenrir-log info "$verbosity" "P11: Running 'git commit -m \"[ АDD ] Tricky\"'.."
 if git commit -m "[ АDD ] Tricky" > "$out" 2> "$err"; then
-    log err "$verbosity" "File has been commited! ('A' is cyrillic)"
-    log warn "$verbosity" "<stdout>" "$(cat "$out")"
-    log err "$verbosity"  "<stderr>" "$(cat "$err")"
+    fenrir-log err "$verbosity" "File has been commited! ('A' is cyrillic)"
+    fenrir-log warn "$verbosity" "<stdout>" "$(cat "$out")"
+    fenrir-log err "$verbosity"  "<stderr>" "$(cat "$err")"
     exit 1
 fi
-log succ "$verbosity" "P11: Hook works correct"
+fenrir-log succ "$verbosity" "P11: Hook works correct"
 
-log info "$verbosity" "P11: Running 'git commit -m \"[ ADD ]Tricky\"'.."
+fenrir-log info "$verbosity" "P11: Running 'git commit -m \"[ ADD ]Tricky\"'.."
 if git commit -m "[ ADD ]Tricky" > "$out" 2> "$err"; then
-    log err "$verbosity" "File has been commited!"
-    log warn "$verbosity" "<stdout>" "$(cat "$out")"
-    log err "$verbosity"  "<stderr>" "$(cat "$err")"
+    fenrir-log err "$verbosity" "File has been commited!"
+    fenrir-log warn "$verbosity" "<stdout>" "$(cat "$out")"
+    fenrir-log err "$verbosity"  "<stderr>" "$(cat "$err")"
     exit 1
-fi
+fenrir-fi
 log succ "$verbosity" "P11: Hook works correct"
 
-log info "$verbosity" "P11: Running 'git commit -m \" [ ADD ] Tricky\"'.."
+fenrir-log info "$verbosity" "P11: Running 'git commit -m \" [ ADD ] Tricky\"'.."
 if git commit -m " [ ADD ] Tricky" > "$out" 2> "$err"; then
-    log err "$verbosity" "File has been commited!"
-    log warn "$verbosity" "<stdout>" "$(cat "$out")"
-    log err "$verbosity"  "<stderr>" "$(cat "$err")"
+    fenrir-log err "$verbosity" "File has been commited!"
+    fenrir-log warn "$verbosity" "<stdout>" "$(cat "$out")"
+    fenrir-log err "$verbosity"  "<stderr>" "$(cat "$err")"
     exit 1
 fi
-log succ "$verbosity" "P11: Hook works correct"
+fenrir-log succ "$verbosity" "P11: Hook works correct"
 
-log info "$verbosity" "P11: Running 'git commit -m \"[ ADD ] Triсky\"'.."
+fenrir-log info "$verbosity" "P11: Running 'git commit -m \"[ ADD ] Triсky\"'.."
 if git commit -m "[ ADD ] Triсky" > "$out" 2> "$err"; then
-    log err "$verbosity" "File has been commited! ('с' is cyrillic)"
-    log warn "$verbosity" "<stdout>" "$(cat "$out")"
-    log err "$verbosity"  "<stderr>" "$(cat "$err")"
+    fenrir-log err "$verbosity" "File has been commited! ('с' is cyrillic)"
+    fenrir-log warn "$verbosity" "<stdout>" "$(cat "$out")"
+    fenrir-log err "$verbosity"  "<stderr>" "$(cat "$err")"
     exit 1
 fi
-log succ "$verbosity" "P11: Hook works correct"
+fenrir-log succ "$verbosity" "P11: Hook works correct"
 
-log info "$verbosity" "P11: Running 'git commit -m \"[ ADD ] Good\"'.."
+fenrir-log info "$verbosity" "P11: Running 'git commit -m \"[ ADD ] Good\"'.."
 if ! git commit -m "[ ADD ] Good" > "$out" 2> "$err"; then
-    log err "$verbosity" "File has not been commited!"
-    log warn "$verbosity" "<stdout>" "$(cat "$out")"
-    log err "$verbosity"  "<stderr>" "$(cat "$err")"
+    fenrir-log err "$verbosity" "File has not been commited!"
+    fenrir-log warn "$verbosity" "<stdout>" "$(cat "$out")"
+    fenrir-log err "$verbosity"  "<stderr>" "$(cat "$err")"
     exit 1
 fi
-log succ "$verbosity" "P11: Hook works correct"
+fenrir-log succ "$verbosity" "P11: Hook works correct"
 
 git reset --soft HEAD~1
 
-log info "$verbosity" "P11: Running 'git commit -m \"[ FIX ] Go0od\"'.."
+fenrir-log info "$verbosity" "P11: Running 'git commit -m \"[ FIX ] Go0od\"'.."
 if ! git commit -m "[ FIX ] Good" > "$out" 2> "$err"; then
-    log err "$verbosity" "File has not been commited!"
-    log warn "$verbosity" "<stdout>" "$(cat "$out")"
-    log err "$verbosity"  "<stderr>" "$(cat "$err")"
+    fenrir-log err "$verbosity" "File has not been commited!"
+    fenrir-log warn "$verbosity" "<stdout>" "$(cat "$out")"
+    fenrir-log err "$verbosity"  "<stderr>" "$(cat "$err")"
     exit 1
 fi
-log succ "$verbosity" "P11: Hook works correct"
+fenrir-log succ "$verbosity" "P11: Hook works correct"
 
 git reset --soft HEAD~1
 
-log info "$verbosity" "P11: Running 'git commit -m \"[ DEL ] 1G1o1O1d1\"'.."
+fenrir-log info "$verbosity" "P11: Running 'git commit -m \"[ DEL ] 1G1o1O1d1\"'.."
 if ! git commit -m "[ DEL ] 1G1o1O1d1" > "$out" 2> "$err"; then
-    log err "$verbosity" "File has not been commited!"
-    log warn "$verbosity" "<stdout>" "$(cat "$out")"
-    log err "$verbosity"  "<stderr>" "$(cat "$err")"
+    fenrir-log err "$verbosity" "File has not been commited!"
+    fenrir-log warn "$verbosity" "<stdout>" "$(cat "$out")"
+    fenrir-log err "$verbosity"  "<stderr>" "$(cat "$err")"
     exit 1
 fi
-log succ "$verbosity" "P11: Hook works correct"
+fenrir-log succ "$verbosity" "P11: Hook works correct"
 
-add-points "$points"
+fenrir-add-points "$points"
 
-log succ "$verbosity" "P11: PASSED"
+fenrir-log succ "$verbosity" "P11: PASSED"
 
diff --git a/git/ess/part-5 b/git/ess/part-5
--- a/git/ess/part-5
+++ b/git/ess/part-5
@@ -7,54 +7,54 @@ out="/var/fenrir/out"
 err="/var/fenrir/err"
 
 
-log info "$verbosity" "P5: Validating commits tree.."
+fenrir-log info "$verbosity" "P5: Validating commits tree.."
 
-if ! branch-exists "$verbosity" "$repo" "10"; then
-        log err "$verbosity" "P5: Terminating.."
-        exit 1
-fi
-
-if ! git branch -a --contains origin/9~2 | grep -q 7; then
-    log err "$verbosity" "P5: Incorrect rebase or extra commits present"
+if ! fenrir-branch-exists "$verbosity" "$repo" "10"; then
+    fenrir-log err "$verbosity" "P5: Terminating.."
     exit 1
 fi
 
-if [ "$(commit-name "origin/10~0")" != 'Revert "21"' ] || \
-   [ "$(commit-name "origin/10~1")" != "23" ] || \
-   [ "$(commit-name "origin/10~2")" != "22" ] || \
-   [ "$(commit-name "origin/10~3")" != "21" ]; then
-        log err "$verbosity" "P5: You have not undone the changes"
+if ! git branch -a --contains 9~2 | grep -q 7; then
+    fenrir-log err "$verbosity" "P5: Incorrect rebase or extra commits present"
+    exit 1
+fi
+
+if [ "$(fenrir-commit-name "10~0")" != 'Revert "21"' ] || \
+   [ "$(fenrir-commit-name "10~1")" != "23" ] || \
+   [ "$(fenrir-commit-name "10~2")" != "22" ] || \
+   [ "$(fenrir-commit-name "10~3")" != "21" ]; then
+        fenrir-log err "$verbosity" "P5: You have not undone the changes"
         exit 1
 fi
 
-log info "$verbosity" "P5: Validating files content.."
+fenrir-log info "$verbosity" "P5: Validating files content.."
 
-if git show -s --format=%b origin/10 | grep "This reverts commit abcee" > "$out" 2> "$err"; then
-    if git show origin/10:5.txt > "$out" 2> "$err"; then
+if git show -s --format=%b 10 | grep "This reverts commit abcee" > "$out" 2> "$err"; then
+    if git show 10:5.txt > "$out" 2> "$err"; then
         content=$(cat "$out")
 
         if [ "$(echo "$content" | wc -w)" -eq 3 ] && \
            [ "$(echo "$content" | sed '1p;d')" = "1" ] && \
            [ "$(echo "$content" | sed '2p;d')" = "2" ] && \
            [ "$(echo "$content" | sed '3p;d')" = "3" ]; then
-                add-points "$points"
+                fenrir-add-points "$points"
         else
-            log err "$verbosity" "P5 Incorrect files content"
-            log warn "$verbosity" "<stdout>" "$(cat "$out")"
-            log err "$verbosity" "<stderr>" "$(cat "$err")"
+            fenrir-log err "$verbosity" "P5 Incorrect files content"
+            fenrir-log warn "$verbosity" "<stdout>" "$(cat "$out")"
+            fenrir-log err "$verbosity" "<stderr>" "$(cat "$err")"
             exit 1
         fi
     else
-        log err "$verbosity" "P5: Error while reading file"
-        log warn "$verbosity" "<stdout>" "$(cat "$out")"
-        log err "$verbosity" "<stderr>" "$(cat "$err")"
+        fenrir-log err "$verbosity" "P5: Error while reading file"
+        fenrir-log warn "$verbosity" "<stdout>" "$(cat "$out")"
+        fenrir-log err "$verbosity" "<stderr>" "$(cat "$err")"
         exit 1
     fi
 else
-    log err "$verbosity" "P5: Incorrect commit body"
-    log warn "$verbosity" "<stdout>" "$(cat "$out")"
-    log err "$verbosity" "<stderr>" "$(cat "$err")"
+    fenrir-log err "$verbosity" "P5: Incorrect commit body"
+    fenrir-log warn "$verbosity" "<stdout>" "$(cat "$out")"
+    fenrir-log err "$verbosity" "<stderr>" "$(cat "$err")"
     exit 1
 fi
 
-log succ "$verbosity" "P5: PASSED"
+fenrir-log succ "$verbosity" "P5: PASSED"
diff --git a/git/ess/part-6 b/git/ess/part-6
--- a/git/ess/part-6
+++ b/git/ess/part-6
@@ -5,18 +5,18 @@ repo=$1
 verbosity=$2
 
 
-log info "$verbosity" "P6: Validating commits tree.."
+fenrir-log info "$verbosity" "P6: Validating commits tree.."
 
-if ! branch-exists "$verbosity" "$repo" "11"; then
-        log err "$verbosity" "P6: Terminating.."
-        exit 1
+if ! fenrir-branch-exists "$verbosity" "$repo" "11"; then
+    fenrir-log err "$verbosity" "P6: Terminating.."
+    exit 1
 fi
 
-if [ "$(commit-hash "origin/11")" != '12a0b906' ]; then
-        log err "$verbosity" "P6: Invalid last commit"
-        log err "$verbosity" "P6: Expected <$(commit-hash "origin/11")> to be <12a0b906>"
-        exit 1
+if [ "$(fenrir-commit-hash "11")" != '12a0b906' ]; then
+    fenrir-log err "$verbosity" "P6: Invalid last commit"
+    fenrir-log err "$verbosity" "P6: Expected <$(fenrir-commit-hash "11")> to be <12a0b906>"
+    exit 1
 fi
 
-add-points "$points"
-log succ "$verbosity" "P6: PASSED"
+fenrir-add-points "$points"
+fenrir-log succ "$verbosity" "P6: PASSED"
diff --git a/git/ess/part-7 b/git/ess/part-7
--- a/git/ess/part-7
+++ b/git/ess/part-7
@@ -5,24 +5,24 @@ repo=$1
 verbosity=$2
 
 
-log info "$verbosity" "P7: Validating commits tree.."
+fenrir-log info "$verbosity" "P7: Validating commits tree.."
 
-if ! branch-exists "$verbosity" "$repo" "12"; then
-        log err "$verbosity" "P7: Terminating.."
+if ! fenrir-branch-exists "$verbosity" "$repo" "12"; then
+        fenrir-log err "$verbosity" "P7: Terminating.."
         exit 1
 fi
 
-if [ "$(commit-name "origin/12")" != '27' ]; then
-        log err "$verbosity" "P7: Invalid last commit"
-        log err "$verbosity" "P7: Expected <$(commit-name "origin/12")> to be <27>"
+if [ "$(fenrir-commit-name "12")" != '27' ]; then
+        fenrir-log err "$verbosity" "P7: Invalid last commit"
+        fenrir-log err "$verbosity" "P7: Expected <$(fenrir-commit-name "12")> to be <27>"
         exit 1
 fi
 
-if [ "$(commit-parent "origin/12")" != '5c468f81' ]; then
-        log err "$verbosity" "P7: Invalid last commit"
-        log err "$verbosity" "P7: Expected <$(commit-parent "origin/12")> to be <5c468f81>"
+if [ "$(fenrir-commit-parent "12")" != '5c468f81' ]; then
+        fenrir-log err "$verbosity" "P7: Invalid last commit"
+        fenrir-log err "$verbosity" "P7: Expected <$(fenrir-commit-parent "12")> to be <5c468f81>"
         exit 1
 fi
 
-add-points "$points"
-log succ "$verbosity" "P7: PASSED"
+fenrir-add-points "$points"
+fenrir-log succ "$verbosity" "P7: PASSED"
diff --git a/git/ess/part-9 b/git/ess/part-9
--- a/git/ess/part-9
+++ b/git/ess/part-9
@@ -6,25 +6,25 @@ verbosity=$2
 out="/var/fenrir/out"
 err="/var/fenrir/err"
 
-log info "$verbosity" "P9: Validating commits tree.."
+fenrir-log info "$verbosity" "P9: Validating commits tree.."
 
-if ! branch-exists "$verbosity" "$repo" "14" || \
-   ! branch-exists "$verbosity" "$repo" "15"; then
-        log err "$verbosity" "P9: Terminating.."
+if ! fenrir-branch-exists "$verbosity" "$repo" "14" || \
+   ! fenrir-branch-exists "$verbosity" "$repo" "15"; then
+        fenrir-log err "$verbosity" "P9: Terminating.."
         exit 1
 fi
 
-if [ "$(commit-name "origin/14~0")" != '6003' ] || \
-   [ "$(commit-name "origin/14~1")" != '6006' ] || \
-   [ "$(commit-hash "origin/14~1")" != '4e7b0f2b' ] || \
-   [ "$(commit-hash "origin/15~0")" != '3319f09d' ]; then
-        log err "$verbosity" "P9: Invalid commit tree"
+if [ "$(fenrir-commit-name "14~0")" != '6003' ] || \
+   [ "$(fenrir-commit-name "14~1")" != '6006' ] || \
+   [ "$(fenrir-commit-hash "14~1")" != '4e7b0f2b' ] || \
+   [ "$(fenrir-commit-hash "15~0")" != '3319f09d' ]; then
+        fenrir-log err "$verbosity" "P9: Invalid commit tree"
         exit 1
 fi
 
-log info "$verbosity" "P9: Validating file content.."
+fenrir-log info "$verbosity" "P9: Validating file content.."
 
-if git show origin/14:9.txt > "$out" 2> "$err"; then
+if git show 14:9.txt > "$out" 2> "$err"; then
     content=$(cat "$out")
 
     if [ "$(echo "$content" | wc -w)" -eq 4 ] && \
@@ -32,19 +32,19 @@ if git show origin/14:9.txt > "$out" 2> "$err"; then
        [ "$(echo "$content" | sed '2p;d')" = "4" ] && \
        [ "$(echo "$content" | sed '3p;d')" = "3" ] && \
        [ "$(echo "$content" | sed '4p;d')" = "2" ]; then
-            add-points "$points"
+            fenrir-add-points "$points"
     else
-        log err "$verbosity" "P9: Incorrect files content"
-        log warn "$verbosity" "<stdout>" "$(cat "$out")"
-        log err "$verbosity" "<stderr>" "$(cat "$err")"
+        fenrir-log err "$verbosity" "P9: Incorrect files content"
+        fenrir-log warn "$verbosity" "<stdout>" "$(cat "$out")"
+        fenrir-log err "$verbosity" "<stderr>" "$(cat "$err")"
         exit 1
     fi
 else
-    log err "$verbosity" "P9: Something went wrong while reading the file"
-    log warn "$verbosity" "<stdout>" "$(cat "$out")"
-    log err "$verbosity" "<stderr>" "$(cat "$err")"
+    fenrir-log err "$verbosity" "P9: Something went wrong while reading the file"
+    fenrir-log warn "$verbosity" "<stdout>" "$(cat "$out")"
+    fenrir-log err "$verbosity" "<stderr>" "$(cat "$err")"
     exit 1
 fi
 
 
-log succ "$verbosity" "P9: PASSED"
+fenrir-log succ "$verbosity" "P9: PASSED"
