Update 5 files
- /git/ad-nib/submodules
- /git/ad-nib/rebase
- /git/ad-nib/hooks
- /git/ad-nib/pipeline.hel
- /git/ad-nib/lfs

diff --git a/git/ad-nib/lfs b/git/ad-nib/lfs
--- a/git/ad-nib/lfs
+++ b/git/ad-nib/lfs
@@ -1,59 +1,20 @@
 #! /usr/bin/env loki
 
-loki-set-log-prefix "RB: "
+loki-set-log-prefix "LFS: "
 
-function commit-hash {
-    git show -s --format="%h" "$1"
-}
-
-
-loki-log info "Validating commits tree.."
-
-if ! fenrir-change-branch "1" || \
-   ! fenrir-change-branch "2"; then
-        loki-log err "Terminating.."
-        exit 1
-fi
-
-merge_commit=$(git log --merges --format="%h" 1)
-
-if [ -z "$merge_commit" ]; then
-    loki-log err "You haven't merged branch"
+if ! fenrir-change-branch "lfs"; then
+    loki-log err "Terminating.."
     exit 1
 fi
 
-if ! [ "$merge_commit" = "$(commit-hash "1~0")" ]; then
-    loki-log err "Expected the merge commit to be the latest"
-    exit 1
+if ! [ -f logo.png ]; then
+    loki-log err "File 'logo.png' was not found"
+    exit 2
 fi
 
-merge_commit=$(git log --merges --format="%h" 2)
+loki-assert-eq "46417a170bd3af222ada40222e992a8ff3121048465e4db45fc86abbfc447f83" "$(cat logo.png | shasum -a 256 | cut -f1 -d' ')"
 
-if [ -n "$merge_commit" ]; then
-    loki-log err "Encountered merge commits in branch <2>"
-    exit 1
-fi
+loki-assert-eq 1 "$(git lfs ls-files | wc -l | tr -d "$IFS")"
+lokiw -e -u "git lfs locks | grep -q logo.png"
 
-if ! [ "$(git show -s --format="%s" "1~0")" = "3" ]; then
-    loki-log err "Expected commit message to be <3>"
-    exit 1
-fi
-
-loki-log info "Validating files content.."
-
-lokiw -e git show 1:1.b
-content=$(loki-get-out)
-
-if [ "$(echo "$content" | wc -w)" -eq 3 ] && \
-   [ "$(echo "$content" | sed '1p;d')" = "A" ] && \
-   [ "$(echo "$content" | sed '2p;d')" = "B" ] && \
-   [ "$(echo "$content" | sed '3p;d')" = "C" ]; then
-
-    lokiw git show 1:2.b || {
-        loki-points +10
-        exit 0
-    }
-fi
-
-loki-log fail "Incorrect files content"
-exit 1
+loki-points +10
