Update 8 files
- /bash/lu/index.json
- /bash/lu/pipeline.json
- /bash/lu/pipeline.hel
- /bash/lu/index.hel
- /bash/lu/broken-matrix
- /bash/lu/large-Id
- /bash/lu/large-matrix
- /bash/lu/small-matrix

diff --git a/bash/lu/broken-matrix b/bash/lu/broken-matrix
--- a/bash/lu/broken-matrix
+++ b/bash/lu/broken-matrix
@@ -1,10 +1,8 @@
-#! /bin/bash
+#! /usr/bin/env loki
 
-# repo=$1
-verbosity=${2-"$1"}
-destination=$(fenrir-getroot)
+destination=$(fenrir-read-conf main root)
 
-fenrir-log info "$verbosity" "BM: Running on broken csv (no LF).."
+loki-log info "BM: Running on broken csv (no LF).."
 
 # Setup logs
 src="/etc/fenrir/in_broken.csv"
@@ -14,35 +12,33 @@ u="/etc/fenrir/u_broken.csv"
 out="/var/fenrir/out"
 err="/var/fenrir/err"
 
-out_l=$(fenrir-tmp 2> /dev/null || mktemp)
-out_u=$(fenrir-tmp 2> /dev/null || mktemp)
+out_l=$(fenrir-tmp)
+out_u=$(fenrir-tmp)
 
-in_matrix=$(fenrir-tmp 2> /dev/null || mktemp)
+in_matrix=$(fenrir-tmp)
 cp "$src" "$in_matrix"
 
 echo "Бугагашеньки" > "$out_u"
-echo "Buzzinga" > "$out_l"
+echo "Buzzinga"     > "$out_l"
 
-if ! "$destination/bash/lu/decomposition.sh" "$in_matrix" "$out_l" "$out_u" "1" > "$out" 2> "$err"; then
-    fenrir-log err "$verbosity" "BM: Script execution has failed"
-    fenrir-log warn "$verbosity" "<stdout>" "$(cat "$out")"
-    fenrir-log err "$verbosity" "<stderr>" "$(cat "$err")"
+if ! lokiw "$destination/bash/lu/decomposition.sh" "$in_matrix" "$out_l" "$out_u" "1"; then
+    loki-log fail "BM: Script execution has failed"
     exit 1
 fi
 
 if ! diff --minimal "$in_matrix" "$src"; then
-    fenrir-log err "$verbosity" "BM: You have modified source matrix"
+    loki-log err "BM: You have modified source matrix"
     exit 4
 fi
 
 if ! diff --minimal "$out_l" "$l"; then
-    fenrir-log err "$verbosity" "BM: Wrong L matrix"
+    loki-log err "BM: Wrong L matrix"
     exit 3
 fi
 
 if ! diff --minimal "$out_u" "$u"; then
-    fenrir-log err "$verbosity" "BM: Wrong U matrix"
+    loki-log err "BM: Wrong U matrix"
     exit 2
 fi
 
-fenrir-log succ "$verbosity" "BM: PASSED"
+loki-log succ "BM: PASSED"
diff --git a/bash/lu/large-Id b/bash/lu/large-Id
--- a/bash/lu/large-Id
+++ b/bash/lu/large-Id
@@ -1,20 +1,16 @@
-#! /bin/bash
+#! /usr/bin/env loki
 
-# repo=$1
-verbosity=${2-"$1"}
-destination=$(fenrir-getroot)
 
-out="/var/fenrir/out"
-err="/var/fenrir/err"
+destination=$(fenrir-read-conf main root)
 
 # Setup logs
-src=$(fenrir-tmp 2> /dev/null || mktemp)
-l=$(fenrir-tmp 2> /dev/null || mktemp)
-u=$(fenrir-tmp 2> /dev/null || mktemp)
+src=$(fenrir-tmp)
+l=$(fenrir-tmp)
+u=$(fenrir-tmp)
 
 dim=25
 
-fenrir-log info "$verbosity" "LID: Testing identity matrix with dim='$dim'"
+loki-log info "LID: Testing identity matrix with dim='$dim'"
 
 {
     for (( i = 0; i < dim - 1; ++i )); do
@@ -36,33 +32,31 @@ fenrir-log info "$verbosity" "LID: Testing identity matrix with dim='$dim'"
     echo "1"
 } >> "$src"
 
-in_matrix=$(mktemp)
+in_matrix=$(fenrir-tmp)
 cp "$src" "$in_matrix"
 
-if ! "$destination/bash/lu/decomposition.sh" "$in_matrix" "$l" "$u" "0" > "$out" 2> "$err"; then
-    fenrir-log err "$verbosity" "LID: Script execution has failed"
-    fenrir-log warn "$verbosity" "<stdout>" "$(cat "$out")"
-    fenrir-log err "$verbosity" "<stderr>" "$(cat "$err")"
+if ! lokiw "$destination/bash/lu/decomposition.sh" "$in_matrix" "$l" "$u" "0"; then
+    loki-log fail "LID: Script execution has failed"
     exit 1
 fi
 
 if ! diff --minimal "$in_matrix" "$src"; then
-    fenrir-log err "$verbosity" "LID: You have modified source matrix"
+    loki-log err "LID: You have modified source matrix"
     exit 4
 fi
 
 if ! diff --minimal "$l" "$src"; then
-    fenrir-log err "$verbosity" "LID: Wrong L matrix"
+    loki-log err "LID: Wrong L matrix"
     exit 3
 fi
 
 if ! diff --minimal "$u" "$src"; then
-    fenrir-log err "$verbosity" "LID: Wrong U matrix"
+    loki-log err "LID: Wrong U matrix"
     exit 2
 fi
 
-fenrir-log succ "$verbosity" "LID: PASSED"
+loki-log succ "LID: PASSED"
 
 # Successfully passed all tests
-fenrir-add-points 100
+loki-points +100
 
diff --git a/bash/lu/large-matrix b/bash/lu/large-matrix
--- a/bash/lu/large-matrix
+++ b/bash/lu/large-matrix
@@ -1,10 +1,8 @@
-#! /bin/bash
+#! /usr/bin/env loki
 
-# repo=$1
-verbosity=${2-"$1"}
-destination=$(fenrir-getroot)
+destination=$(fenrir-read-conf main root)
 
-fenrir-log info "$verbosity" "LM: Running on large matrix (7x7).."
+loki-log info "LM: Running on large matrix (7x7).."
 
 # Setup logs
 src="/etc/fenrir/in_large.csv"
@@ -14,32 +12,30 @@ u="/etc/fenrir/u_large.csv"
 out="/var/fenrir/out"
 err="/var/fenrir/err"
 
-out_l="$HOME/l.csv"
-out_u="$HOME/u.csv"
+out_l=$(fenrir-tmp)
+out_u=$(fenrir-tmp)
 
-in_matrix=$(fenrir-tmp 2> /dev/null || mktemp)
+in_matrix=$(fenrir-tmp)
 cp "$src" "$in_matrix"
 
-if ! "$destination/bash/lu/decomposition.sh" "$in_matrix" "$out_l" "$out_u" "3" > "$out" 2> "$err"; then
-    fenrir-log err "$verbosity" "LM: Script execution has failed"
-    fenrir-log warn "$verbosity" "<stdout>" "$(cat "$out")"
-    fenrir-log err "$verbosity" "<stderr>" "$(cat "$err")"
+if ! lokiw "$destination/bash/lu/decomposition.sh" "$in_matrix" "$out_l" "$out_u" "3"; then
+    loki-log fail "LM: Script execution has failed"
     exit 1
 fi
 
 if ! diff --minimal "$in_matrix" "$src"; then
-    fenrir-log err "$verbosity" "LM: You have modified source matrix"
+    loki-log err "LM: You have modified source matrix"
     exit 4
 fi
 
 if ! diff --minimal "$out_l" "$l"; then
-    fenrir-log err "$verbosity" "LM: Wrong L matrix"
+    loki-log err "LM: Wrong L matrix"
     exit 3
 fi
 
 if ! diff --minimal "$out_u" "$u"; then
-    fenrir-log err "$verbosity" "LM: Wrong U matrix"
+    loki-log err "LM: Wrong U matrix"
     exit 2
 fi
 
-fenrir-log succ "$verbosity" "LM: PASSED"
+loki-log succ "LM: PASSED"
diff --git a/bash/lu/small-matrix b/bash/lu/small-matrix
--- a/bash/lu/small-matrix
+++ b/bash/lu/small-matrix
@@ -1,45 +1,39 @@
-#! /bin/bash
+#! /usr/bin/env loki
 
-# repo=$1
-verbosity=${2-"$1"}
-destination=$(fenrir-getroot)
 
-fenrir-log info "$verbosity" "SM: Running on small matrix (3x3).."
+destination=$(fenrir-read-conf main root)
+
+loki-log info "SM: Running on small matrix (3x3).."
 
 # Setup logs
 src="/etc/fenrir/in_small.csv"
 l="/etc/fenrir/l_small.csv"
 u="/etc/fenrir/u_small.csv"
 
-out="/var/fenrir/out"
-err="/var/fenrir/err"
+out_l=$(fenrir-tmp)
+out_u=$(fenrir-tmp)
 
-out_l="$HOME/l.csv"
-out_u="$HOME/u.csv"
-
-in_matrix=$(fenrir-tmp 2> /dev/null || mktemp)
+in_matrix=$(fenrir-tmp)
 cp "$src" "$in_matrix"
 
-if ! "$destination/bash/lu/decomposition.sh" "$in_matrix" "$out_l" "$out_u" "2" > "$out" 2> "$err"; then
-    fenrir-log err "$verbosity" "SM: Script execution has failed"
-    fenrir-log warn "$verbosity" "<stdout>" "$(cat "$out")"
-    fenrir-log err "$verbosity" "<stderr>" "$(cat "$err")"
+if ! lokiw "$destination/bash/lu/decomposition.sh" "$in_matrix" "$out_l" "$out_u" "2"; then
+    loki-log fail "SM: Script execution has failed"
     exit 1
 fi
 
 if ! diff --minimal "$in_matrix" "$src"; then
-    fenrir-log err "$verbosity" "SM: You have modified source matrix"
+    loki-log err "SM: You have modified source matrix"
     exit 4
 fi
 
 if ! diff --minimal "$out_l" "$l"; then
-    fenrir-log err "$verbosity" "SM: Wrong L matrix"
+    loki-log err "SM: Wrong L matrix"
     exit 3
 fi
 
 if ! diff --minimal "$out_u" "$u"; then
-    fenrir-log err "$verbosity" "SM: Wrong U matrix"
+    loki-log err "SM: Wrong U matrix"
     exit 2
 fi
 
-fenrir-log succ "$verbosity" "SM: PASSED"
+loki-log succ "SM: PASSED"
